<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Pitch, Hit, Profit</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-b15df86742554840d07b04d0f56a07e9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">


<meta name="citation_title" content="Pitch, Hit, Profit">
<meta name="citation_author" content="Andrew Cerqui">
<meta name="citation_author" content="Jace Higa">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=The sportsbook edge: Understanding how the house always wins;,citation_abstract=Summary This article explains how sportsbooks maintain a built-in edge by structuring odds to favor the them. It details how -110 odds require bettors to win more than 52.4% of bets to break even, highlighting the impact of vig on long-term profitability.;,citation_author=undefined Naomi;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://allthepicks.com/betting-edge/;">
<meta name="citation_reference" content="citation_title=Exploiting sports-betting market using machine learning;,citation_abstract=The study developed a profitable sports betting system using three novel components: (1) explicitly reducing correlation with bookmaker predictions while maintaining accuracy, (2) using convolutional neural networks for player-level feature aggregation, and (3) applying modern portfolio theory for optimal bet distribution. The system achieved systematic positive returns on NBA data from 2006-2014.;,citation_author=Ondřej Hubáček;,citation_author=Gustav Šourek;,citation_author=Filip Železný;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_fulltext_html_url=https://www.sciencedirect.com/science/article/abs/pii/S156849461930007X;,citation_doi=10.1016/j.asoc.2019.105654;,citation_issn=1568-4946;,citation_volume=83;,citation_journal_title=Applied Soft Computing;">
<meta name="citation_reference" content="citation_title=Use of machine learning and deep learning to predict the outcomes of major league baseball matches;,citation_abstract=Compared 1DCNN, ANN, and SVM models for MLB prediction using 2019 season data. Achieved highest prediction accuracies of 93.4%, 93.91%, and 93.90% respectively before feature selection, and 94.18% and 94.16% with ANN and SVM after feature selection. This was the first application of 1DCNN to MLB prediction.;,citation_author=Mei-Ling Huang;,citation_author=Yi-Zhen Li;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_fulltext_html_url=https://www.mdpi.com/2076-3417/11/10/4499;,citation_issue=10;,citation_doi=10.3390/app11104499;,citation_issn=2076-3417;,citation_volume=11;,citation_journal_title=Applied Sciences;">
<meta name="citation_reference" content="citation_title=Exploring and selecting features to predict the next outcomes of MLB games;,citation_abstract=Developed a comprehensive feature selection framework for MLB prediction, analyzing which statistics provide the most predictive value for game outcomes. The study systematically evaluated different combinations of batting, pitching, and situational variables to optimize prediction accuracy.;,citation_author=Shuo-Fang Li;,citation_author=Mei-Ling Huang;,citation_author=Yi-Zhen Li;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8871522/;,citation_issue=2;,citation_doi=10.3390/e24020264;,citation_issn=1099-4300;,citation_volume=24;,citation_journal_title=Entropy;">
<meta name="citation_reference" content="citation_title=Machine learning for sports betting: Should model selection be based on accuracy or calibration?;,citation_abstract=Tested whether calibration or accuracy should drive model selection for sports betting. Using NBA data, found that selecting models based on calibration rather than accuracy led to dramatically better returns: +34.69% ROI versus -35.17% ROI. In the best case scenario, calibration-based selection achieved +36.93% versus +5.56% for accuracy-based selection.;,citation_author=Sean Walsh;,citation_author=Mayukh Joshi;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_fulltext_html_url=https://www.sciencedirect.com/science/article/pii/S266682702400015X;,citation_doi=10.1016/j.frl.2024.104814;,citation_issn=1544-6123;,citation_volume=60;,citation_journal_title=Finance Research Letters;">
<meta name="citation_reference" content="citation_title=A systematic review of machine learning in sports betting: Techniques, challenges, and future directions;,citation_abstract=Comprehensive review of ML applications in sports betting across multiple sports. Found that ensemble methods consistently outperform single models, with particular success in combining different algorithm types. For baseball specifically, identified that Markov processes and machine learning algorithms to predict pitch types and game outcomes show promise, emphasizing detailed pitch data importance.;,citation_author=René Manassé Galekwa;,citation_author=undefined colleagues;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_fulltext_html_url=https://arxiv.org/html/2410.21484v1;,citation_journal_title=arXiv preprint arXiv:2410.21484;">
<meta name="citation_reference" content="citation_title=MLB game outcome prediction using machine learning;,citation_abstract=Investigated MLB game outcome prediction using random forests and XGBoost with historical Retrosheet data (1930-2016). Achieved 55.52% accuracy in predicting game outcomes as binary classification using XGBoost with season data only, outperforming random guessing and simple home team prediction.;,citation_author=T. Elfrink;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_publisher=University of Pennsylvania;">
<meta name="citation_reference" content="citation_title=Efficient spread betting markets: A literature review;,citation_abstract=Are simple trading strategies profitable? It is a question that has been on the minds of academics and practitioners for decades. In this paper, we review the longstanding literature on trading strategies in spread betting (also known as handicap betting), a popular sports betting microstructure. We review over 600 strategy implementations and find that market efficiency and systematic misperceptions are not mutually exclusive per se. Predictable glitches occur, but they are too small to be profitably exploited which is consistent with efficient markets.;,citation_author=Jonas Vandenbruaene;,citation_author=Jan Annaert;,citation_author=Marc De Ceuster;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://journals.sagepub.com/doi/10.1177/15270025211071042;,citation_issue=4;,citation_doi=10.1177/15270025211071042;,citation_issn=1527-0025;,citation_volume=23;,citation_journal_title=Journal of Sports Economics;">
</head>

<body class="quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Pitch, Hit, Profit</h1>
            <p class="subtitle lead">A Data-Backed Approach to Projecting Favorable Outcomes in MLB Betting</p>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
        
        <div class="quarto-title-meta">

                <div>
            <div class="quarto-title-meta-heading">Authors</div>
            <div class="quarto-title-meta-contents">
                        <p>Andrew Cerqui </p>
                        <p>Jace Higa </p>
                      </div>
          </div>
                
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      </div>
    </div>



    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">Background</a>
  <ul class="collapse">
  <li><a href="#sports-betting-market-structure-and-efficiency" id="toc-sports-betting-market-structure-and-efficiency" class="nav-link" data-scroll-target="#sports-betting-market-structure-and-efficiency">Sports Betting Market Structure and Efficiency</a></li>
  <li><a href="#predictive-modeling-in-baseball-analytics" id="toc-predictive-modeling-in-baseball-analytics" class="nav-link" data-scroll-target="#predictive-modeling-in-baseball-analytics">Predictive Modeling in Baseball Analytics</a></li>
  <li><a href="#strategic-approaches-to-sports-betting" id="toc-strategic-approaches-to-sports-betting" class="nav-link" data-scroll-target="#strategic-approaches-to-sports-betting">Strategic Approaches to Sports Betting</a></li>
  <li><a href="#research-gaps-and-methodological-innovation" id="toc-research-gaps-and-methodological-innovation" class="nav-link" data-scroll-target="#research-gaps-and-methodological-innovation">Research Gaps and Methodological Innovation</a></li>
  <li><a href="#mlb-as-an-analytical-environment" id="toc-mlb-as-an-analytical-environment" class="nav-link" data-scroll-target="#mlb-as-an-analytical-environment">MLB as an Analytical Environment</a></li>
  <li><a href="#research-objective-and-contribution" id="toc-research-objective-and-contribution" class="nav-link" data-scroll-target="#research-objective-and-contribution">Research Objective and Contribution</a></li>
  <li><a href="#ethical-considerations" id="toc-ethical-considerations" class="nav-link" data-scroll-target="#ethical-considerations">Ethical Considerations</a>
  <ul class="collapse">
  <li><a href="#data-privacy-and-sources" id="toc-data-privacy-and-sources" class="nav-link" data-scroll-target="#data-privacy-and-sources">Data Privacy and Sources</a></li>
  <li><a href="#responsible-gambling-considerations" id="toc-responsible-gambling-considerations" class="nav-link" data-scroll-target="#responsible-gambling-considerations">Responsible Gambling Considerations</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">Data Sources</a>
  <ul class="collapse">
  <li><a href="#statsapi" id="toc-statsapi" class="nav-link" data-scroll-target="#statsapi">statsapi</a></li>
  <li><a href="#mlb.com" id="toc-mlb.com" class="nav-link" data-scroll-target="#mlb.com">mlb.com</a></li>
  <li><a href="#baseball-savant" id="toc-baseball-savant" class="nav-link" data-scroll-target="#baseball-savant">Baseball Savant</a></li>
  <li><a href="#pybaseball" id="toc-pybaseball" class="nav-link" data-scroll-target="#pybaseball">pybaseball</a></li>
  <li><a href="#oddsapi" id="toc-oddsapi" class="nav-link" data-scroll-target="#oddsapi">oddsapi</a></li>
  </ul></li>
  <li><a href="#data-organization" id="toc-data-organization" class="nav-link" data-scroll-target="#data-organization">Data Organization</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#overunder-run-scoring-analysis" id="toc-overunder-run-scoring-analysis" class="nav-link" data-scroll-target="#overunder-run-scoring-analysis">Over/Under Run Scoring Analysis</a>
  <ul class="collapse">
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a></li>
  <li><a href="#actual-vs.-expected-batting-average" id="toc-actual-vs.-expected-batting-average" class="nav-link" data-scroll-target="#actual-vs.-expected-batting-average">Actual vs.&nbsp;Expected Batting Average</a></li>
  </ul></li>
  <li><a href="#machine-learning-for-overunders" id="toc-machine-learning-for-overunders" class="nav-link" data-scroll-target="#machine-learning-for-overunders">Machine Learning for Over/Unders</a>
  <ul class="collapse">
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering">Feature Engineering</a></li>
  <li><a href="#model-performance" id="toc-model-performance" class="nav-link" data-scroll-target="#model-performance">Model Performance</a></li>
  <li><a href="#feature-importance" id="toc-feature-importance" class="nav-link" data-scroll-target="#feature-importance">Feature Importance</a></li>
  </ul></li>
  <li><a href="#prop-betting-analysis-for-batters" id="toc-prop-betting-analysis-for-batters" class="nav-link" data-scroll-target="#prop-betting-analysis-for-batters">Prop Betting Analysis for Batters</a>
  <ul class="collapse">
  <li><a href="#pitcher-batter-preview" id="toc-pitcher-batter-preview" class="nav-link" data-scroll-target="#pitcher-batter-preview">Pitcher-Batter Preview</a></li>
  </ul></li>
  <li><a href="#machine-learning-for-individual-player-props" id="toc-machine-learning-for-individual-player-props" class="nav-link" data-scroll-target="#machine-learning-for-individual-player-props">Machine Learning for Individual Player Props</a>
  <ul class="collapse">
  <li><a href="#model-development-and-methodology" id="toc-model-development-and-methodology" class="nav-link" data-scroll-target="#model-development-and-methodology">Model Development and Methodology</a></li>
  <li><a href="#model-performance-and-validation" id="toc-model-performance-and-validation" class="nav-link" data-scroll-target="#model-performance-and-validation">Model Performance and Validation</a></li>
  <li><a href="#integration-with-real-sportsbook-odds" id="toc-integration-with-real-sportsbook-odds" class="nav-link" data-scroll-target="#integration-with-real-sportsbook-odds">Integration with Real Sportsbook Odds</a></li>
  <li><a href="#financial-performance-and-market-testing" id="toc-financial-performance-and-market-testing" class="nav-link" data-scroll-target="#financial-performance-and-market-testing">Financial Performance and Market Testing</a></li>
  <li><a href="#market-efficiency-and-sportsbook-performance" id="toc-market-efficiency-and-sportsbook-performance" class="nav-link" data-scroll-target="#market-efficiency-and-sportsbook-performance">Market Efficiency and Sportsbook Performance</a></li>
  <li><a href="#practical-implementation-and-future-directions" id="toc-practical-implementation-and-future-directions" class="nav-link" data-scroll-target="#practical-implementation-and-future-directions">Practical Implementation and Future Directions</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a>
  <ul class="collapse">
  <li><a href="#overunder-runs-bets" id="toc-overunder-runs-bets" class="nav-link" data-scroll-target="#overunder-runs-bets">Over/Under Runs Bets</a></li>
  <li><a href="#prop-bets" id="toc-prop-bets" class="nav-link" data-scroll-target="#prop-bets">Prop Bets</a></li>
  <li><a href="#implications" id="toc-implications" class="nav-link" data-scroll-target="#implications">Implications</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">Appendix</a>
  <ul class="collapse">
  <li><a href="#data-dictionary" id="toc-data-dictionary" class="nav-link" data-scroll-target="#data-dictionary">Data Dictionaries</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">




  


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Sports betting has grown rapidly in popularity, fueled by increased legalization, media coverage, and widespread access to online platforms. For many, it remains a form of entertainment, but could it be something more? With the right data and strategy, is it possible to consistently identify favorable opportunities and gain an edge over the market? Specifically, can a data-driven approach to betting, particularly in Major League Baseball (MLB), serve as a viable income stream?</p>
<p>Baseball is a team sport played between two sides of nine players, where the goal is to score runs by hitting a pitched ball and advancing around four bases. Teams alternate between offense (batting) and defense (pitching and fielding), with each half-inning ending after three outs. A standard game consists of nine innings. While the rules are relatively simple, modern baseball stands out as one of the most analytically advanced professional sports. Its one-on-one matchups and slower pace of play make it easier to isolate and track a wide range of distinct metrics in real time. Teams routinely analyze batter-pitcher matchups, pitching tendencies, and situational probabilities to gain a competitive edge—making baseball particularly appealing for data-driven sports betting.</p>
<p>With the rise of advanced statistics, particularly expected metrics, and real-time data, bettors now have a wide range of wagering options. These include moneylines (who wins the game), over/unders (total runs scored), and player proposition bets (prop bets), which are specific bettable outcomes related to an individual player’s performance in a game. These include things like hits, will a player get a hit in this game (yes or no), and total bases, which track how many bases a player earns through hits in a given game. Despite the abundance of vailablity of data, many sports bettors rely on their intuition and personal biases– an approach that seldom results in sustained success. Compounding this challenge is the fact that sportsbooks maintain a built-in edge through the way odds are structured. For example, in an evenly matched game, both teams are typically listed at -110 odds rather than +100. This means a $100 winning bet would return just $90.90 in profit, rather than $100, creating a margin that favors the sportsbook. Thus, in this context users would have to win more than 52.4% of their bets to just break even <span class="citation" data-cites="AllThePicksEdge2023">(<a href="#ref-AllThePicksEdge2023" role="doc-biblioref">Naomi 2023</a>)</span>.</p>
<p>In this context, leveraging the vast amount of granular baseball data becomes crucial. With its rich statistical history and highly measurable in-game actions, baseball stands out as one of the most data-intensive and analytically advanced sports. It offers bettors an opportunity to apply data-driven strategies and models to gain an edge over the market.</p>
<p>We aim to investigate whether recent player performance, historical trends, advanced metrics, and variations in sportsbook odds can be leveraged to identify profitable opportunities in Major League Baseball betting markets.</p>
</section>
<section id="background" class="level1">
<h1>Background</h1>
<p>This background section examines the theoretical and practical foundations for data-driven sports betting research. We first explore how modern sports betting markets operate and where pricing inefficiencies might exist, particularly for individual player propositions. We then review the evolution of predictive modeling in baseball analytics and how machine learning approaches have been applied to sports betting. Finally, we identify key research gaps in integrating statistical modeling with market analysis, setting the stage for our hybrid methodology that combines bottom-up player performance prediction with top-down market opportunity identification.</p>
<section id="sports-betting-market-structure-and-efficiency" class="level2">
<h2 class="anchored" data-anchor-id="sports-betting-market-structure-and-efficiency">Sports Betting Market Structure and Efficiency</h2>
<p>The legalization of online sports betting across multiple jurisdictions has created increasingly sophisticated and competitive markets. However, research on sports betting market efficiency shows mixed results—different sports and bet types demonstrate varying levels of pricing accuracy <span class="citation" data-cites="Hubacek2019">(<a href="#ref-Hubacek2019" role="doc-biblioref">Hubáček, Šourek, and Železný 2019</a>)</span>.</p>
<p>Main game betting markets (like who wins the game) tend to be efficiently priced due to high betting volumes and extensive professional analysis. In contrast, individual player proposition bets often show greater pricing disparities. These player prop markets receive less analytical attention and have lower betting volumes, potentially creating opportunities for systematic data-driven approaches.</p>
<p>The fundamental challenge for any betting strategy remains the house edge built into sportsbook pricing. Standard odds structures ensure that sportsbooks maintain mathematical advantages even in competitive markets, requiring bettors to identify opportunities where their expected value exceeds the built-in profit margins. This edge varies across bet types and operators, with player propositions often carrying higher margins than main game markets.</p>
</section>
<section id="predictive-modeling-in-baseball-analytics" class="level2">
<h2 class="anchored" data-anchor-id="predictive-modeling-in-baseball-analytics">Predictive Modeling in Baseball Analytics</h2>
<p>Baseball analytics has evolved dramatically since the introduction of sabermetrics, with modern machine learning applications achieving increasingly sophisticated prediction capabilities. <span class="citation" data-cites="Huang2021">(<a href="#ref-Huang2021" role="doc-biblioref">Huang and Li 2021</a>)</span> demonstrated that statistical models could achieve over 94% accuracy in MLB game outcome prediction using advanced feature selection techniques, while <span class="citation" data-cites="Li2022">(<a href="#ref-Li2022" role="doc-biblioref">Li, Huang, and Li 2022</a>)</span> developed comprehensive frameworks for identifying the most predictive baseball statistics.</p>
<p>However, a critical insight from <span class="citation" data-cites="Walsh2024">(<a href="#ref-Walsh2024" role="doc-biblioref">Walsh and Joshi 2024</a>)</span> revealed that prediction accuracy and betting profitability represent fundamentally different goals. Their research showed that models optimized for probability calibration achieved +34.69% ROI compared to -35.17% for accuracy-focused approaches. Calibration refers to how well a model’s predicted probabilities match actual outcome frequencies—for example, events predicted with 30% probability should actually occur about 30% of the time. This is crucial for betting because accurate probability estimates are needed to identify when market odds offer value, regardless of whether the model correctly predicts the outcome. This finding suggests that traditional machine learning evaluation metrics such as accuracy, precision, and recall may actually be counterproductive for betting applications.</p>
<p>Recent research has increasingly focused on ensemble methods for sports prediction, such as <span class="citation" data-cites="Galekwa2024">(<a href="#ref-Galekwa2024" role="doc-biblioref">Galekwa and colleagues 2024</a>)</span> findings that combining multiple algorithms consistently outperforms single-model approaches. This supports developing comprehensive modeling frameworks that leverage multiple analytical techniques rather than relying on individual algorithms.</p>
</section>
<section id="strategic-approaches-to-sports-betting" class="level2">
<h2 class="anchored" data-anchor-id="strategic-approaches-to-sports-betting">Strategic Approaches to Sports Betting</h2>
<p>Sports betting research traditionally distinguishes between two methodological approaches. Bottom-up strategies involve building statistical models to predict outcomes more accurately than sportsbooks do. These approaches use player performance data, matchup analysis, and advanced metrics to generate probability estimates that might reveal when market odds are mispriced.</p>
<p>Top-down strategies focus on comparing odds across different sportsbooks to identify pricing inefficiencies. Rather than predicting game outcomes, these approaches look for discrepancies in how different operators price the same events, capitalizing on situations where one book offers significantly better odds than others.</p>
<p>While both approaches have shown promise independently, existing literature has not rigorously examined whether combining bottom-up predictive modeling with top-down market analysis provides superior results compared to using either methodology alone.</p>
</section>
<section id="research-gaps-and-methodological-innovation" class="level2">
<h2 class="anchored" data-anchor-id="research-gaps-and-methodological-innovation">Research Gaps and Methodological Innovation</h2>
<p>A significant gap exists in formal examination of hybrid approaches that integrate predictive modeling with market analysis. While practitioners may informally blend these strategies, academic research has not evaluated whether such integration provides superior risk-adjusted returns.</p>
<p>This gap is particularly notable given the complementary nature of these approaches, statistical modeling excels at identifying undervalued performance patterns, while market analysis can identify optimal timing and execution strategies. The combination potentially addresses the primary weaknesses of each individual approach.</p>
<p>Furthermore, much existing research focuses on prediction accuracy rather than practical implementation, often overlooking critical factors such as bankroll management or market access limitations. These practical considerations are essential for translating theoretical success into real-world profitability.</p>
</section>
<section id="mlb-as-an-analytical-environment" class="level2">
<h2 class="anchored" data-anchor-id="mlb-as-an-analytical-environment">MLB as an Analytical Environment</h2>
<p>Baseball presents unique advantages for data-driven betting analysis due to its extensive statistical history and granular performance data. The sport’s discrete, measurable events enable precise statistical modeling, while Statcast technology has created opportunities for advanced analytical approaches incorporating biomechanical measurements and contact quality metrics.</p>
<p>The individual nature of many baseball events—particularly batter versus pitcher matchups—creates natural opportunities for player proposition betting that may be less efficiently priced than team outcomes. Two of the most common player propositions involve hits and total bases. Hit markets typically offer over/under wagers on whether a player will record more than 0.5 hits (at least one hit) or 1.5 hits (multiple hits) in a game. Total bases represent the cumulative value of a player’s hits: singles count as one base, doubles as two, triples as three, and home runs as four. Common total bases markets include over/under 1.5 or 2.5 bases.</p>
<p>These individual performance markets offer analytical advantages over team-based betting. Player propositions depend primarily on individual skill and recent form rather than complex team dynamics, creating more predictable statistical patterns. The large number of games throughout the baseball season provides substantial sample sizes for analysis while creating numerous daily opportunities for profitable betting.</p>
<p>Recent research has identified significant variation in sportsbook accuracy across different types of baseball bets, with player propositions showing greater pricing disparities between operators compared to primary game markets <span class="citation" data-cites="Vandenbruaene2022">(<a href="#ref-Vandenbruaene2022" role="doc-biblioref">Vandenbruaene, Annaert, and Ceuster 2022</a>)</span>.</p>
</section>
<section id="research-objective-and-contribution" class="level2">
<h2 class="anchored" data-anchor-id="research-objective-and-contribution">Research Objective and Contribution</h2>
<p>Our investigation addresses the identified research gap by developing and evaluating complementary approaches that demonstrate both top-down and bottom-up methodologies for MLB player proposition betting. The first approach develops interactive tools for situational matchup analysis, enabling detailed examination of pitcher-batter historical performance and contextual factors that may reveal betting opportunities on a case-by-case basis.</p>
<p>The second approach employs calibrated machine learning models trained on comprehensive player performance data to generate probabilistic assessments, which are then systematically compared against real sportsbook odds from multiple operators to identify value opportunities. This hybrid methodology focuses on analysis of individual player propositions across large volumes of daily betting markets.</p>
<p>This dual-methodology investigation provides novel contributions to sports betting literature by rigorously implementing both approaches and examining their respective strengths for different aspects of the sports betting challenge. The research advances understanding of line pricing variations in proposition betting and provides practical insights into where different data-driven approaches may be most effective.</p>
</section>
<section id="ethical-considerations" class="level2">
<h2 class="anchored" data-anchor-id="ethical-considerations">Ethical Considerations</h2>
<p>We next wanted to address potential ethical issues before we get further into our work. These ethical considerations are important because our analytical findings can influence real-world behavior and financial decisions; thus acknowledging limits and risks helps prevent harm and misuse. Stating our standards up front also strengthens the integrity and reproducibility of the research and ensures alignment with responsible gambling and legal frameworks.</p>
<section id="data-privacy-and-sources" class="level3">
<h3 class="anchored" data-anchor-id="data-privacy-and-sources">Data Privacy and Sources</h3>
<p>The data utilized in this research consists entirely of publicly available information from professional baseball games, including Statcast measurements, player performance statistics, and sportsbook pricing data from both regulated and offshore operators. No personally identifiable information beyond public player names and performance metrics was collected. All data represents factual, objective measures that are routinely published within the sports analytics community.</p>
</section>
<section id="responsible-gambling-considerations" class="level3">
<h3 class="anchored" data-anchor-id="responsible-gambling-considerations">Responsible Gambling Considerations</h3>
<p>The primary ethical consideration in this research concerns its potential application to sports betting activities. Several critical limitations and risks must be emphasized:</p>
<p><strong>No Guaranteed Profits</strong>: Even when positive expected value opportunities are identified, variance inherent in probabilistic outcomes means that substantial losses remain possible over both short and extended periods. Historical performance does not guarantee future results.</p>
<p><strong>Variance and Risk Management</strong>: The high variance of sports betting means that even systematically profitable approaches can experience extended losing streaks that individuals may not be able to endure. Anyone considering application of these findings must thoroughly understand proper bankroll management principles and position sizing (deciding how much money to bet on each wager) strategies.</p>
<p><strong>Problem Gambling Risks</strong>: Sports betting can lead to significant financial harm and may negatively affect mental health. We strongly advise anyone considering wagering to seek education on responsible gambling practices and never risk money they cannot afford to lose. Betting should be approached cautiously and within personal limits.</p>
<p><strong>Market Evolution</strong>: Betting markets continuously evolve as operators adjust to new information. Any identified inefficiencies may diminish as markets adapt, potentially rendering historical findings obsolete.</p>
<p><strong>Disclaimer</strong>: This research is conducted for academic purposes only. Any application of these findings to actual betting activities is undertaken entirely at the user’s own risk. The authors accept no responsibility for financial losses that may result from application of this research. Readers are strongly encouraged to thoroughly research proper bankroll management techniques and to seek professional guidance on responsible gambling practices before placing any wagers.</p>
</section>
</section>
</section>
<section id="data" class="level1">
<h1>Data</h1>
<p>Our dataset was built by combining information from multiple sources, each selected for its relevance to MLB performance and wagering analysis. Together, these sources contributed complementary perspectives and enabled us to perform the kind of matchup-level analysis needed to explore profitability and uncover potential edges in the betting market.</p>
<section id="data-sources" class="level2">
<h2 class="anchored" data-anchor-id="data-sources">Data Sources</h2>
<p>We collected data from five sources, which are outlined in greater detail in the following sections. StatsAPI, pybaseball, and oddsapi were accessed using a custom Python scraper that called their respective APIs directly, allowing us to ingest structured data on player performance, advanced metrics, and betting markets. This approach differed from our Selenium-based web scraper used later for MLB.com, which required automated browser interaction to extract dynamically loaded content not available through the APIs. Finally, we sourced supplemental tracking data from Baseball Savant by downloading static CSV files. Together, these pipelines enabled a comprehensive, multi-source dataset suitable for statistical analysis, machine learning, and real-world validation.</p>
<section id="statsapi" class="level3">
<h3 class="anchored" data-anchor-id="statsapi">statsapi</h3>
<p>The first source was Major League Baseball’s public API, accessed using the statsapi Python package. This provided structured JSON data containing player metadata, team identifiers, game results, and detailed per-game statistics for batters and pitchers. This source served as the foundation for our dataset. To automate collection, we deployed the scraper on Railway, a cloud platform that lets us run and schedule scripts automatically without needing to manage any servers. We scheduled our scripts to runs daily at 7:00 AM PST, retrieving the previous day’s game data. The raw JSON was parsed using SQL queries in PostgreSQL and loaded into a set of normalized relational tables.</p>
<p>Our tables included players, teams, games, sides, batter_stats, and pitcher_stats. The players table contains a list of all individuals who appeared in at least one Major League Baseball game from June 21st to the present, each assigned a unique player_id for consistent identification. The teams table includes all 30 MLB teams, each mapped to a unique team_id, enabling team-level joins and analysis. The sides table identifies which team played as the home or away team in each game, an important distinction in baseball since the home team bats second and may have strategic advantages. The batter_stats and pitcher_stats tables store detailed per-game box score data, separated by hitting statistics and pitching statistics. These stats include traditional metrics such as hits, home runs, and strikeouts for batters, and innings pitched, earned runs, and walks for pitchers. The use of primary keys such as player_id, game_id, and team_id allowed for seamless joins across tables. This structure enables efficient querying across player appearances, game contexts, and performance metrics, while remaining flexible enough to incorporate additional data sources such as advanced Statcast metrics and other tracking metrics.</p>
</section>
<section id="mlb.com" class="level3">
<h3 class="anchored" data-anchor-id="mlb.com">mlb.com</h3>
<p>Our second data source was MLB’s official website, mlb.com, which we scraped using Selenium, a Python package for automated browser interaction. This approach allowed us to extract pre-game matchup information from MLB.com’s preview pages, data not available through the public Stats API. Specifically, we captured scheduled starting pitchers and projected batter matchups, along with historical hitter performance against the opposing pitcher. It enabled us to factor in pre-game context and generate predictions ahead of each day’s games. The scraper was designed to click into each game’s “Preview” button, capture the relevant information, then return to the main page and repeat this process for all games scheduled on a given day. This scraper was deployed on Railway and scheduled to run slightly earlier than the StatsAPI job, at 6:55 AM PST. Unlike the StatsAPI scraper, it focused on collecting information for games scheduled later that same day.</p>
<p>A major challenge with this source was the absence of standardized identifiers such as player or game IDs. To address this, we created a composite key in the preview table using a combination of game_date, batter_name, and pitcher_name to uniquely identify each record. The JSON data gathered was unstructured so it required an extensive use of regular expressions (REGEX), which made the parsing process significantly more complex.</p>
<p>In the end, we produced a table called previews, which included the game date, projected starting pitcher, and historical performance data of each batter against that pitcher– such as home runs, at-bats, and batting average. This table allowed us to enrich our dataset by linking valuable pre-game context with actual in-game performance, enabling more nuanced analyses of matchups and outcomes.</p>
</section>
<section id="baseball-savant" class="level3">
<h3 class="anchored" data-anchor-id="baseball-savant">Baseball Savant</h3>
<p>To supplement our scraped data, we incorporated a third source: Baseball Savant, a publicly available website that provides detailed, season-long statistics that go beyond traditional box scores. Unlike our other sources, which offered game-by-game data, Baseball Savant’s data is cumulative and tracks advanced metrics throughout the season. For example, it includes expected batting average which incorporates exit velocity (how hard the ball is hit) and launch angle (angle at which the player swings their bat) and pitch usage rates, which displays how frequently pitchers throw specific pitch types. The site offers the ability to download the data as CSV files, which we did during the All-Star break to capture a midseason snapshot of player performance. For the purposes of our analysis, we chose to download the data once, as the season is already more than halfway complete and player performance is unlikely to vary significantly over the remaining games. After downloading the CSV files, we cleaned the data by removing unnecessary columns and renaming fields to improve clarity and ensure consistency across our dataset.</p>
<p>The processed data was stored in four normalized tables within our PostgreSQL database. The batter_pitches table captured how individual batters performed against specific pitch types—such as fastballs, sliders, and curveballs. It included advanced metrics like Run Value (a measure of how much a specific pitch type increases or decreases run expectancy when thrown to that specific batter) and expected batting average to estimate likely outcomes. Similarly, the pitcher_pitches table reflected how effective each pitcher was with their various pitch types, using the same set of metrics but from the pitcher’s perspective. The pitcher_statcast table provided aggregated performance statistics that were not pitch-specific, offering a broader view of each pitchers season-level tendencies. This Statcast data was particularly valuable as it combined pitch-level insights with overall performance metrics, enabling a more complete evaluation of both hitters and pitchers.</p>
</section>
<section id="pybaseball" class="level3">
<h3 class="anchored" data-anchor-id="pybaseball">pybaseball</h3>
<p>Our next source was the pybaseball Python package, which provided extended access to MLB’s Statcast system and allowed us to retrieve season-level statistics. This data enriched our dataset with advanced metrics, including batted ball tracking (which measures factors like exit velocity and hit direction), pitch characteristics, and sabermetric indicators (which provide expected values for more precise performance evaluation). Using pybaseball.statcast(), we collected pitch-level data spanning over a full season, which was then aggregated into player-game summaries. We were also able to extract seasonal statistics for batters, adding broader context around batter performance.</p>
<p>To unify these sources, we used the players table to bridge the gap between the detailed Statcast tracking data and the rest of our dataset. By matching on player_id, as in earlier integrations, we successfully connected granular tracking metrics with season-level statistics for 537 unique players. This join allowed us to capture both game-level performance details and broader, long-term trends across the season.</p>
<p>Only historical data was needed, so our scraper ran once, and the collected data was stored in the batter_statcast table. This table followed a similar structure to pitcher_statcast, but included season-level summaries instead of data limited to the current year. All data was pushed into PostgreSQL, where this structure supported querying across pitch-level, game-level, and seasonal data, laying the groundwork for downstream modeling and analysis.</p>
</section>
<section id="oddsapi" class="level3">
<h3 class="anchored" data-anchor-id="oddsapi">oddsapi</h3>
<p>Our betting market data was sourced using the OddsAPI feed, which provided structured JSON data on sportsbook offerings for player props such as hits, total bases, and home runs. This information was retrieved using the same custom scraper architecture used in other parts of the project. For consistency and integration with our game-level data, we joined odds records to player performance using a combination of game date and team abbreviations, ensuring alignment across sources despite the absence of shared unique identifiers.</p>
<p>The betting data was parsed and stored in PostgreSQL, using fields such as market_type (type of prop bet), price (decimal odds), and point (over/under threshold). We captured a historical snapshot of the betting odds, preserving how sportsbooks were pricing specific player outcomes at a given moment in time. This static reference point allowed us to compare market expectations to actual player performance, which was especially valuable during model training and evaluation. While the dataset does not yet include full odds histories or line movement over time, the current structure still enables a direct link between sportsbook predictions and individual player-game results.</p>
<p>This integration supports downstream use cases such as model backtesting and value identification. This integration supports downstream use cases such as model backtesting and value identification. Backtesting refers to the process of applying a predictive model to historical data to evaluate how well it would have performed in real-world scenarios– for example, simulating bets on past games based on model predictions and comparing the results to actual outcomes. Value identification involves comparing the model’s predicted probabilities for specific player outcomes (e.g., getting a hit or hitting a home run). By comparing predicted player outcomes to market-implied probabilities from sportsbooks, we can evaluate model performance not only in terms of accuracy but also potential profitability. This alignment creates a clear path for analysis centered on identifying inefficiencies in publicly posted betting lines.</p>
</section>
</section>
<section id="data-organization" class="level2">
<h2 class="anchored" data-anchor-id="data-organization">Data Organization</h2>
<p>In the end the data was organized and combined using third normal form (3NF) to minimize redundancy and maintain reliable links across related data. Our entity-relationship diagram (ERD) (<a href="#fig-erd">Figure 1</a>) provides a clear visual representation, clearly mapping the relationships among all entities derived from our data acquisition process.</p>
<figure id="fig-erd" class="figure">
<a href="images/erd_diagram.png"><img src="images/erd_diagram.png" class="img-fluid figure-img" alt="ERD diagram"></a>
<figcaption style="font-size: 10px; color: #555;">
<strong>Figure 1</strong>: This diagram illustrates how our database schema is organized to support complex querying and analysis. At the center, the players, games, and teams tables form the relational backbone, linking to performance-specific tables like batter_stats, pitcher_stats, and their Statcast counterparts. The previews and player_props tables bring in pre-game context and betting market data, while sides defines home/away team roles per game. This structure, normalized to third normal form (3NF), allows us to seamlessly join historical performance, matchup context, and betting odds—enabling detailed statistical modeling, matchup evaluation, and value detection at both the player and game levels.
</figcaption>
</figure>
<p><a href="#data-dictionary">See Data Dictionary</a></p>
</section>
</section>
<section id="results" class="level1 page-columns page-full">
<h1>Results</h1>
<p>Using the full dataset we compiled, we now turn to a focused analysis aimed at uncovering actionable edges for MLB betting. We start by modeling team run scoring to identify the strongest drivers of offense, then evaluate a classifier for over/under outcomes at the 4.5-run threshold. We follow that up with hitter-level prop work that combines matchup histories, pitch-type run values, and calibrated ML models which link predictions to historical sportsbook odds to test realized profitability.</p>
<section id="overunder-run-scoring-analysis" class="level2">
<h2 class="anchored" data-anchor-id="overunder-run-scoring-analysis">Over/Under Run Scoring Analysis</h2>
<p>Our initial analysis focused on identifying which variables were most predictive of how many runs a team scores in a given game. We used a wide range of features grouped into three main categories:</p>
<ul>
<li><p><strong>Opposing starting pitcher (sp.)</strong>: Including metrics such as earned run average (ERA), opponent batting average (BA), innings pitched (IP), and expected stats like xERA and xBA.</p></li>
<li><p><strong>Opposing relief pitcher statistics (rp.)</strong>: Represented aggregated bullpen performance using the same types of measures as for starters, such as ERA and slugging percentage (SLG) allowed.</p></li>
</ul>
<p>– <strong>Team batter statistics (b.)</strong>: Covered both per-game aggregates (e.g., total hits, home runs, strikeouts) and season-long averages for the lineup, such as batting average (BA) and slugging percentage (SLG).</p>
<p>By integrating data from opposing starting pitchers, opposing relievers, and the team’s offensive performance, we aimed to construct a well-rounded model for predicting team run performance.</p>
<section id="exploratory-data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h3>
<p>To gain insight into team scoring behavior, we computed summary statistics for runs scored per game. This helped us examine the distribution of offensive output and understand typical scoring ranges across all team-game observations.</p>
<figure id="fig-run_dist" class="figure">
<img src="images/run_dist.png" alt="Run Distribution" width="800" class="figure-img">
<figcaption style="font-size: 10px; color: #555;">
<strong>Figure 2</strong>: The distribution of runs scored per game across all teams from June 21 to the present is right-skewed, with most teams scoring between 3 and 7 runs. Extreme high-scoring games (10+ runs) are relatively rare, while shutouts and 1-run games are pretty common.
</figcaption>
</figure>
<p>The distribution of runs scored per game, as seen in <a href="#fig-run_dist">Figure 2</a>, was right-skewed, with a few high-scoring outliers pulling the mean upward. The median was 4 runs, while the mean was slightly higher at 4.6, reflecting the impact of those outliers. This mean value serves as a useful benchmark when modeling run production in machine learning, especially when deciding how to frame our prediction target.</p>
<p>We then focused on identifying which features were most indicative of how many runs a team scores in a game. To do this, we built a linear regression model using a wide range of pitching and hitting statistics. However, many baseball statistics are derived from overlapping components, making them inherently correlated. For example, batting average is one of several inputs used to calculate weighted on-base average (wOBA), meaning these two variables are mathematically linked. As a result, including both in a predictive model can introduce multicollinearity, where highly correlated inputs distort the model’s ability to accurately estimate the unique contribution of each feature. To address this, we systematically filtered out redundant variables, prioritizing those that captured unique predictive value. After this reduction process, we finalized a simplified linear model using the following variables: starting pitcher earned run average (<code>sp_era</code>), starting pitcher batting average against (<code>sp_ba</code>), starting pitcher slugging percentage against (<code>sp_slg</code>), relief pitcher earned run average (<code>rp_era</code>), relief pitcher slugging percentage against (<code>rp_slg</code>), relief pitcher innings pitched (<code>rp_ip</code>), team batting average (<code>b_ba</code>), total team strikeouts (<code>b_sum_so</code>), and team slugging percentage (<code>b_slg</code>).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 22%">
<col style="width: 18%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Predictor</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t value</th>
<th>Pr(&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>6.538</td>
<td>2.377</td>
<td>2.751</td>
<td>0.0061 **</td>
</tr>
<tr class="even">
<td>sp_era</td>
<td>-0.135</td>
<td>0.130</td>
<td>-1.042</td>
<td>0.2980</td>
</tr>
<tr class="odd">
<td>sp_ba</td>
<td>4.744</td>
<td>6.150</td>
<td>0.771</td>
<td>0.4408</td>
</tr>
<tr class="even">
<td>sp_slg</td>
<td>-4.021</td>
<td>3.252</td>
<td>-1.236</td>
<td>0.2168</td>
</tr>
<tr class="odd">
<td>rp_era</td>
<td>-0.220</td>
<td>0.095</td>
<td>-2.323</td>
<td>0.0205 *</td>
</tr>
<tr class="even">
<td>rp_slg</td>
<td>3.594</td>
<td>2.329</td>
<td>1.543</td>
<td>0.1232</td>
</tr>
<tr class="odd">
<td>rp_ip</td>
<td>0.224</td>
<td>0.089</td>
<td>2.527</td>
<td>0.0117 *</td>
</tr>
<tr class="even">
<td>b_ba</td>
<td>26.823</td>
<td>11.862</td>
<td>2.261</td>
<td>0.0241 *</td>
</tr>
<tr class="odd">
<td>b_sum_so</td>
<td>0.050</td>
<td>0.045</td>
<td>1.130</td>
<td>0.2589</td>
</tr>
<tr class="even">
<td>b_slg</td>
<td>9.894</td>
<td>5.692</td>
<td>1.738</td>
<td>0.0826 .</td>
</tr>
</tbody>
</table>
<figure id="tab-var" class="figure">
<figcaption style="font-size: 10px; color: #555;">
<strong>Table 1</strong>: Coefficient estimates from a linear regression model predicting team runs scored. The model includes variables related to starting and relief pitcher performance (e.g., ERA, innings pitched, opponent batting metrics), as well as team-level offensive statistics such as batting average, slugging percentage, and total strikeouts. Each coefficient reflects the estimated change in runs scored associated with a one-unit increase in the corresponding predictor, holding all other variables constant. Statistically significant predictors (p &lt; 0.05) are marked with an asterisk (*), indicating a meaningful relationship with run production.
</figcaption>
</figure>
<p>From our linear model, we identified three statistically significant predictors of runs scored (p &lt; 0.05):</p>
<ul>
<li><p>Relief pitcher innings pitched (<code>rp_ip</code>), with a p-value of 0.0117</p></li>
<li><p>Relief pitcher ERA (<code>rp_era</code>), with a p-value of 0.0205</p></li>
<li><p>Team batting average (<code>b_ba</code>), with a p-value of 0.0241</p></li>
</ul>
<p>Batting average stood out as something worth exploring further, especially as the season progresses, since we also have data on expected batting average (xBA) available.</p>
</section>
<section id="actual-vs.-expected-batting-average" class="level3">
<h3 class="anchored" data-anchor-id="actual-vs.-expected-batting-average">Actual vs.&nbsp;Expected Batting Average</h3>
<p>The law of averages suggest that after a large number of trials, outcomes tend to stabilize and move closer to their long-run tendencies. In the context of baseball, this implies that a team’s observed batting average may begin to reflect their underlying hitting ability over time. While not a mathematical guarantee, this principle provides context for using modeled statistics. Model-derived metrics are not a true statistical expectation, but it does serve as a useful benchmark for identifying under- or over-performance across the season.</p>
<p>Expected batting average is a Statcast metric designed to estimate the likelihood that a batted ball will result in a hit, which refers to any batted ball that results in the batter safely reaching at least first base without the benefit of an error. The metric is based on two key factors: exit velocity (how hard the ball is hit) and the launch angle (the vertical angle, in degrees, at which the ball leaves the bat relative to the ground). Baseball results can be unpredictable and are influenced by baseball alignments. As a result, traditional stats do not always measure how well a player is actually performing. That is where expected statistics come in– through data they provide a more accurate picture of a player’s performance. For example, a hitter might crush a ball at 115 MPH, but if it’s hit directly at a defender, it results in an out. On the other hand, a softly hit ball at just 40 MPH could drop into the perfect spot for a hit. xBA accounts for these inconsistencies by using historical data to estimate how often similar batted balls have gone for hits. While not perfect, it offers a more context-aware view of hitting performance. The following graph, (<a href="#fig-ba">Figure 3</a>), compares each team’s actual batting average to their xBA, helping us see who has been overperforming or underperforming based on quality of contact.</p>
<figure id="fig-ba" class="figure">
<img src="images/ba.png" alt="Batting Average" width="800" class="figure-img">
<figcaption style="font-size: 10px; color: #555;">
<strong>Figure 3</strong>: Comparison of actual batting average (BA) and expected batting average (xBA) for all MLB teams. Each point represents a team’s seasonal averages. The dashed diagonal line indicates where a team’s actual BA equals its xBA– meaning they are performing as expected based on the quality of their contact. Teams plotted above the line are overperforming their expected average (higher BA than xBA would suggest), while those below the line are underperforming (recording a lower BA than expected).
</figcaption>
</figure>
<p>Since we are trying to understand team run production it makes sense to focus on batting average. A higher team batting average means the team is collecting more hits on average, which is essential for generating offense. In baseball, scoring runs typically requires advancing base runners, and hits are one of the primary ways to move players around the bases. The more often players get on base via hits, the more opportunities a team has to bring runners home. While not every hit results in a run, consistent hitting increases the chances of building rallies and ultimately scoring. When a team’s actual batting average is lower than its expected batting average (xBA), it may suggest underperformance, assuming xBA reasonably reflects the quality of contact. While xBA is not a perfect estimate, it offers a standardized way to evaluate whether a team is hitting into bad luck or failing to convert quality contact into results. Over time, if xBA is a reliable reflection of a team’s underlying hitting quality, we would expect actual outcomes to begin aligning with those expectations. Teams underperforming their xBA may see an uptick in batting average, and consequently, run production. Conversely, teams overperforming may experience a decline in their runs as fewer balls in play fewer batted balls result in hits over time. To explore whether these trends actually play out over time, we examined how average run production shifted after MLB’s All-Star Break (ASB) as shown in (<a href="#fig-run_diff">Figure 4</a>).</p>
<figure id="fig-run_diff" class="figure">
<img src="images/run_diff.png" alt="Run Differences" width="800" class="figure-img">
<figcaption style="font-size: 10px; color: #555;">
<strong>Figure 4</strong>: Change in average runs scored per game for MLB teams after the 2024 All-Star Break (ASB) compared to before the break. Positive values (green bars) indicate teams that increased their run production, with the Chicago White Sox (+5.15) showing the largest improvement. Negative values (red bars) indicate teams that scored fewer runs on average after the break, with the Boston Red Sox (-4.33) experiencing the steepest decline. The figure highlights the five teams with the largest increases and decreases, illustrating which offenses surged or struggled to start the second half of the season.
</figcaption>
</figure>
<p>A pattern emerges when comparing team-level batting average (BA) and expected batting average (xBA) to changes in run production after the All-Star Break. Among the largest movers, several teams that had been underperforming their xBA—such as CLE, CWS, KC, and HOU—saw significant increases in runs scored (<a href="#fig-run_diff">Figure 4</a>), consistent with the idea of positive regression. Conversely, some overperforming teams like BOS and SEA experienced declines in run production, aligning with expectations of regression toward the mean. However, the relationship was far from universal– teams like DET and BAL deviated from the expected pattern. This indicates that while xBA may highlight potential for regression, its predictive power appears strongest for certain teams at the extremes and less reliable across the league as a whole. (<a href="#fig-ba2">Figure 5</a>).</p>
<p>The Colorado Rockies (COL) appear to be overperforming their expected batting average (xBA), but this is likely a product of Coors Field– MLB’s most hitter-friendly park. The high altitude and thin air in Denver inflate offensive stats by reducing air resistance and allowing balls to travel farther. This “Coors Field Effect” regularly skews batting metrics, making Colorado’s apparent overperformance more a reflection of park conditions than unsustainable hitting. This highlights the importance of considering contextual factors– such as ballpark effects, strength of schedule, and injuries when interpreting performance metrics. In future work, it would be valuable to explore other factors to add to the depth.</p>
<figure id="fig-ba2" class="figure">
<img src="images/ba2.png" alt="Batting Average Overlayed" width="800" class="figure-img">
<figcaption style="font-size: 10px; color: #555;">
<strong>Figure 5</strong>: Relationship between changes in average runs scored after the All-Star Break and each team’s degree of overperformance or underperformance relative to their expected batting average (xBA). Green indicates teams whose run production has increased, while red indicates teams whose run production has declined.
</figcaption>
</figure>
</section>
</section>
<section id="machine-learning-for-overunders" class="level2">
<h2 class="anchored" data-anchor-id="machine-learning-for-overunders">Machine Learning for Over/Unders</h2>
<p>Following the xBA and run production analysis, we were curious whether setting a clear scoring threshold could reveal additional predictive signals. We framed over/under outcomes in MLB games as a binary classification task– predicting whether a team would score more or fewer than 4.5 runs. This threshold closely mirrors the historical league average of 4.6 runs, providing a relevant and interpretable baseline for evaluation.</p>
<p>We selected a Random Forest algorithm for our classification model due to its strong performance and interpretability. Random Forests are ensemble models that reduce overfitting by aggregating the results of multiple decision trees, leading to more accurate predictions. Additionally, they offer clear insights into feature importance, allowing us to understand which variables most influence model outcomes.</p>
<section id="feature-engineering" class="level3">
<h3 class="anchored" data-anchor-id="feature-engineering">Feature Engineering</h3>
<p>We engineered two key features: the average number of runs a team has scored over its last five games (<code>rolling_runs_5</code>) and the team’s batting average over the same span <code>team_rolling_ba_5</code>. These metrics serve as short-term performance indicators, capturing both a team’s ability to generate runs and its overall hitting effectiveness in recent matchups. By focusing on a five-game window, they provide a timely snapshot of offensive form that can reflect hot streaks, slumps, or the impact of recent roster changes.</p>
<p>Additionally, we incorporated several existing metrics into our model, including the opponent starting pitcher’s expected batting average (sp_x_ba), opponent starting pitcher’s earned run average (sp_era), the starting lineup’s average expected batting average (b_x_ba), and team slugging percentage (b_slg).</p>
</section>
<section id="model-performance" class="level3">
<h3 class="anchored" data-anchor-id="model-performance">Model Performance</h3>
<p>To evaluate the effectiveness of our Random Forest classifier in predicting whether a team would score over or under 4.5 runs, we examined several performance metrics that offer complementary insights into model quality and reliability.</p>
<p>The Area Under the Receiver Operating Characteristic Curve (AUC) was 0.756, reflecting strong discriminative performance. This indicates that, when comparing a randomly selected game in which a team scored over 4.5 runs to one in which it did not, the model assigns a higher probability to the over outcome approximately 76% of the time. Our targeted result can be influenced by a wide range of dynamic and interrelated variables, thus an AUC above 0.75 indicates the model is reliably distinguishing between high and low scoring outcomes. This result suggests that the model is effectively capturing underlying patterns that differentiate high-scoring from low-scoring team performances. This performance is further illustrated by the ROC curve in <a href="#fig-roc">Figure 6</a>, which visualizes the model’s trade-off between sensitivity and specificity across all classification thresholds. The steep initial rise and bowed shape of the curve indicate effective separation between the two classes—teams that scored over 4.5 runs and those that did not—culminating in an AUC of 0.756. This reinforces the model’s reliability in identifying scoring patterns relevant to over/under predictions.</p>
<figure id="fig-roc" class="figure">
<img src="images/roc.png" alt="ROC Graph" width="800" class="figure-img">
<figcaption style="font-size: 10px; color: #555;">
<strong>Figure 6</strong>: ROC curve for the Random Forest model predicting whether a team scores over 4.5 runs. The curve illustrates the trade-off between sensitivity (true positive rate) and specificity (true negative rate). The model shows strong performance, with the curve rising well above the diagonal line
</figcaption>
</figure>
<p>In addition to AUC, overall accuracy provides a more intuitive sense of model correctness. The model achieved an overall accuracy of 72.5%, correctly predicting the outcome in nearly three-quarters of all games. This far exceeds the No Information Rate of 55.8%, which reflects the accuracy one would achieve by always predicting the majority class (in this case teams scoring under 4.5 runs). The substantial lift over this baseline demonstrates that the model is capturing meaningful patterns in the data rather than simply echoing the most frequent outcome. This improvement is particularly noteworthy given the variability of baseball scoring, where small changes in game context, player performance, or even weather conditions can swing results.</p>
<p>We also evaluated sensitivity, which measures how well the model identifies games where a team scored over 4.5 runs. It achieved a rate of 76.6%, meaning that when a team did go over, the model predicted it correctly more than 75% of the time. This level of performance is especially useful in betting contexts, where one would need to predict the over correctly more than 52.4% of the time just to break even. The model’s specificity was 67.2%, indicating that it also performed well at identifying games that went under.</p>
<p>Finally, we considered Cohen’s Kappa, which was 0.44. Unlike raw accuracy, Kappa adjusts for the possibility of correct predictions occurring by chance, offering a more rigorous measure of model agreement. A value of 0.44 indicates moderate agreement beyond chance, reinforcing that the model captures real predictive signals. While not exceptionally high, this level of Kappa still demonstrates that the model performs meaningfully better than random guessing—an important outcome given the inherent variability when predicting team run totals.</p>
<p>Together, these results show that our Random Forest model performs well across both interpretability and predictive accuracy dimensions, making it a valuable tool for forecasting team run production in MLB games.</p>
</section>
<section id="feature-importance" class="level3">
<h3 class="anchored" data-anchor-id="feature-importance">Feature Importance</h3>
<figure id="fig-var" class="figure">
<img src="images/var.png" alt="Important Variables for O/U ML" width="800" class="figure-img">
<figcaption style="font-size: 10px; color: #555;">
<strong>Figure 7</strong>: This figure illustrates the relative importance of each feature in predicting whether a team will score over 4.5 runs. Higher values indicate greater contribution to the model’s predictive accuracy.
</figcaption>
</figure>
<p>The variable importance plot highlights the relative contribution of each feature to the model’s predictive accuracy. Among all inputs, the engineered feature <span style="color: #1f77b4;">rolling_runs_5</span> overwhelmingly emerged as the most influential. This feature, which captures a team’s recent scoring momentum, proved to be the strongest indicator of whether a team would surpass the 4.5 run threshold. Its high importance reinforces the value of short-term performance trends in forecasting offensive output.</p>
<p>Following this, <span style="color: #1f77b4;">team_rolling_ba_5</span>, which represents the team’s batting average over the last five games, also ranked highly. This measure captures the overall quality of a team’s hitting during recent matchups, serving as a gauge of a team’s ability to consistently get hits. Traditional pitching and matchup-based metrics also contributed meaningfully. For instance, <span style="color: #1f77b4;">sp_x_ba</span> and <span style="color: #1f77b4;">sp_era</span>, which reflect the expected batting average and earned run average of the opposing starting pitcher, respectively, helped capture the quality of pitching faced by the offense. These features provide critical context for how difficult it might be for a team to score in a given game. Similarly, <span style="color: #1f77b4;">b_x_ba</span> (expected batting average of the lineup) and <span style="color: #1f77b4;">b_slg</span> (slugging percentage) contributed additional insight into the underlying hitting power and contact quality of the offensive side.</p>
<p>Overall, the combination of short-term offensive momentum, recent team batting metrics, and opposing pitcher quality formed the backbone of the model’s predictive framework. These findings suggest that blending engineered features with traditional matchup statistics enhances the model’s ability to predict over/under outcomes accurately.</p>
</section>
</section>
<section id="prop-betting-analysis-for-batters" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="prop-betting-analysis-for-batters">Prop Betting Analysis for Batters</h2>
<p>We then explored hitter-focused prop bets, specifically whether a batter would record at least one hit or go over/under 1.5 total bases in a given game. Total bases are calculated as one for a single, two for a double, three for a triple, and four for a home run. To hit the over, a player must total at least two bases– for example, by hitting a double, triple, home run, or combining multiple hits such as a single and a double.</p>
<section id="pitcher-batter-preview" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="pitcher-batter-preview">Pitcher-Batter Preview</h3>
<p>To gain an edge in predicting favorable prop outcomes, we began by analyzing game preview data for each day, including scheduled starting pitchers and historical batter-vs-pitcher matchup statistics.</p>
<p>The first areas we explored was how specific batters had performed against certain pitchers in the past. In baseball, it is often said that some hitters “have a pitcher’s number,” meaning they see a pitcher very well— a phenomenon that may not always be captured by traditional stats. This can stem from a batter’s ability to pick up the ball exceptionally well out of a pitcher’s hand or from a strong sense of that pitcher’s tendencies. Thus, when a batter is able to consistently succeed against a particular pitcher, it can signal a meaningful matchup advantage. With that in mind, we prioritized these historical trends as a way to identify potentially favorable prop bet opportunities.</p>
<p>We analyzed discrepancies in run value per 100 pitches (RV/100)– a metric measuring how each pitch changes a team’s run expectancy, with positive values favoring hitters and negative values favoring pitcher. This would aid us in identifying potential pitcher-hitter mismatches. This allowed us to identify potential pitcher-hitter mismatches as we calculated the difference in RV/100 by comparing a batter’s performance against specific pitch types to the different pitches thrown by the scheduled opposing pitcher. This allowed us to estimate how well a batter might match up based on the types of pitches they were likely to face in a given game. In other words, we cross-referenced each batter’s strengths with a pitcher’s weaknesses to uncover matchups where a hitter may be especially well-suited to succeed. To ensure the matchup was meaningful, we also applied a minimum usage threshold, filtering out pitch types that a pitcher rarely throws.</p>
<section id="interactive-hitter-matchup-app" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="interactive-hitter-matchup-app">Interactive Hitter Matchup App</h4>
<p>We wanted a way to translate our findings into a practical, game-day resource, we developed an interactive dashboard designed to point out the most advantageous hitter macthups for each day’s slate of games. The tool identifies situations where a hitter has a statistical edge and allows users to examine supporting statistics, such as matchup histories or run-value differentials.</p>
<p>The top table displays advantageous batter–pitcher matchup histories, filtered to highlight hitters with the strongest track records. We included only hitters with a batting average of .300 or higher against the opposing pitcher– a mark generally considered very good in baseball, indicating the hitter records a hit in at least 30% of their past at-bats. To ensure meaningful results, we also required a minimum of four at-bats in the matchup to provide a more reliable sample size.</p>
<p>The table below highlights batters with a significant advantage based on run value against specific pitch types. It is sorted from highest to lowest run value difference, showcasing hitters who are most likely to succeed against the opposing pitcher’s arsenal. To qualify for this table, a batter must have a run value differential of at least 3 in their favor. If a batter appears in both this table and the matchup history table above, they are highlighted in yellow– indicating that both analyses suggest a strong likelihood of success in that day’s game.</p>
<p>Users can sort the dashboard by date, with the default view automatically displaying matchupss with supporting stats from selected day’s slate of games. If a previous date is selected, historical matchups and their corresponding results will appear. A color-coded key is provided below the date selector to help interpret the meaning of each highlighted row.</p>
<p>At the bottom of the dashboard is a simulated betting analysis. For players to get a hit,it is typically priced around -200 odds, meaning a $200 wager would win $100 in profit. For the purpose of our analysis, we will be assuming a $10 wager per player. A successful bet yields a $5 profit, while a loss forfeits the $10 stake. For total bases (2+), where odds are usually closer to +100, we again simulate $10 wagers. In this case, a win returns $10 in profit, while a loss results in a $10 loss. The dashboard aggregates daily results based on these assumptions and displays the cumulative outcomes for easy tracking.</p>
<div class="column-page">
<div style="text-align:center;">
<iframe src="https://60bwvg-jace-higa.shinyapps.io/best_hitter_matchups/" width="100%" height="800" style="border:none; display:block;" title="Best Hitter Matchups" loading="lazy"> </iframe>
<p style="margin-top:8px; font-style:italic; font-size:0.95em; color:#555;">
<strong>Figure 8:</strong> Interactive dashboard showing advantageous MLB batter props, with hypothetical results displayed as well.
</p>
</div>
</div>
</section>
</section>
</section>
<section id="machine-learning-for-individual-player-props" class="level2">
<h2 class="anchored" data-anchor-id="machine-learning-for-individual-player-props">Machine Learning for Individual Player Props</h2>
<p>While the interactive matchup analysis provided valuable insights into daily opportunities through pitcher-batter historical data and pitch-type analysis, we recognized the need for a scalable, data-driven approach that could systematically evaluate large volumes of prop opportunities. Rather than integrating these approaches directly—which would have been ideal but was not feasible due to the higher cost of real-time odds data required for such integration—we developed a complementary machine learning pipeline that could operate independently while addressing similar prop betting markets. This ML system focused on predicting specific binary outcomes corresponding to common betting markets: whether a player would record at least one hit, at least two hits, and at least two total bases in a game.</p>
<section id="model-development-and-methodology" class="level3">
<h3 class="anchored" data-anchor-id="model-development-and-methodology">Model Development and Methodology</h3>
<p>We framed individual player prop prediction as a binary classification problem, then applied probability calibration to ensure outputs would be suitable for betting applications. While classification accuracy optimizes prediction correctness, calibration adjusts probability estimates to align with observed outcome frequencies—essential for comparing model predictions against betting market prices. This approach follows Walsh &amp; Joshi (2024) research showing calibration-optimized models achieve better ROI in sports betting applications.</p>
<p>Our feature engineering used only information available before game time to avoid data leakage and artificially inflated model performance. We incorporated two types of player metrics: seasonal performance rates and volume-based historical patterns. Seasonal rates included batting average (hits per at-bat), on-base percentage, and slugging percentage, which measure hitting efficiency and quality. Volume-based features like hits per game and home runs per game captured typical production levels. Experience indicators such as games played and total plate appearances (individual batting opportunities) captured player usage patterns rates.</p>
<p>The dataset comprised 19,587 player-game records with strict temporal validation: training on April-May 2025 data (12,000 records), validation on June 2025 (4,000 records), and testing on July 2025 (3,587 records). This temporal structure prevents the model from seeing future information during training, simulating realistic betting scenarios where only past performance can be used to inform future betting decisions. We implemented Random Forest, XGBoost, and ensemble methods with isotonic regression calibration applied to all base models to optimize probability estimates for betting applications.</p>
</section>
<section id="model-performance-and-validation" class="level3">
<h3 class="anchored" data-anchor-id="model-performance-and-validation">Model Performance and Validation</h3>
<p>Before testing market profitability, we validated model performance on historical MLB outcomes using standard machine learning metrics. This sequential approach follows academic best practices: establish predictive capability on known outcomes before attempting market-based validation where multiple factors beyond model accuracy affect results.</p>
<p>The Random Forest model achieved 0.549 test AUC, closely aligning with an established academic baseline of 0.552 AUC (Elfrink, 2018) for MLB prediction tasks. This alignment demonstrates realistic performance expectations rather than artificially inflated metrics which are common in sports betting literature. Feature importance analysis revealed seasonal performance rates provided the primary predictive signal, with batting average, OPS, and wOBA ranking as top contributors. The absence of same-game features from importance rankings confirms successful data leakage prevention, as shown in Figure 9.</p>
<figure id="fig-feature_importance" class="figure">
<img src="images/Model Feature Importance.png" alt="Model Feature Importance" width="800" class="figure-img">
<figcaption style="font-size: 10px; color: #555;">
<strong>Figure 9</strong>: Feature importance analysis aggregated across all models and prediction targets shows that seasonal performance metrics dominate predictive capability. Hit/Game and Batting Average emerge as the strongest predictors, with traditional sabermetric statistics (Slg, OPS, wOBA) providing additional signal. The absence of same-game features confirms successful data leakage prevention.
</figcaption>
</figure>
</section>
<section id="integration-with-real-sportsbook-odds" class="level3">
<h3 class="anchored" data-anchor-id="integration-with-real-sportsbook-odds">Integration with Real Sportsbook Odds</h3>
<p>Having validated model performance on historical outcomes, we integrated predictions with historical odds data from nine major sportsbooks including DraftKings, FanDuel, BetMGM, and Caesars. This integration successfully matched 86.5% of our model predictions with corresponding market odds across 1.2 million player prop records. 100% integration was not possible due to some players not having odds posted for that day or market.</p>
<p>Our value detection algorithm identified betting opportunities where our generated model probabilities exceeded best available odds probabilities by at least 5%. This edge threshold ensures meaningful statistical advantage while accounting for the built-in profit margins that sportsbooks incorporate into their pricing.</p>
<p>Position sizing employed Kelly criterion methodology, which calculates optimal bet size based on the magnitude of the statistical edge and odds offered to maximize long-term growth while controlling risk. We capped all positions at 5% of a $10,000 simulated bankroll to prevent excessive risk from model estimation errors.</p>
</section>
<section id="financial-performance-and-market-testing" class="level3">
<h3 class="anchored" data-anchor-id="financial-performance-and-market-testing">Financial Performance and Market Testing</h3>
<p>Our backtesting analysis covered the period through July 12, 2025, stopping before the All Star Game. Through this period, our model identified 342 value betting opportunities, generating $2,579.21 profit on $132,518.08 wagered for 1.95% ROI. The system achieved a 41.5% win rate with mean return per bet of $7.54 and standard deviation of $460.80, reflecting the high variance inherent in individual bet outcomes. Figure 10 illustrates the volatile profit trajectory characteristic of sports betting applications.</p>
<figure id="fig-cumulative_profit" class="figure">
<img src="images/Test Period Performance.png" alt="Test Period Performance" width="800" class="figure-img">
<figcaption style="font-size: 10px; color: #555;">
<strong>Figure 10</strong>: Cumulative profit performance across 342 value betting opportunities through July 12, 2025. The high volatility pattern illustrates the inherent variance in sports betting outcomes, with significant drawdown periods followed by profitable streaks. Final profit of $2,579.21 represents 1.95% ROI despite substantial intermediate fluctuations.
</figcaption>
</figure>
<p>Given this high variance environment, we conducted comprehensive statistical validation to assess whether our results represent genuine predictive capability and profitable edge or could have occurred by chance. Bootstrap analysis—repeatedly sampling our betting results with replacement—with 10,000 resamples generated a 95% confidence interval of [-$40.92, $56.78] for average profit per bet. This wide interval, spanning both positive and negative values, reflects the substantial uncertainty inherent in our relatively small sample size.</p>
<p>Our effect size analysis revealed a standardized effect of 0.016 (Cohen’s d), indicating a very small magnitude that falls well below conventional thresholds for meaningful effects in other fields. However, even a small edge in sports betting can be very profitable over time, assuming this edge is true and did not occur by chance. Permutation testing, which randomly shuffles our profit/loss results to simulate the null hypothesis of no predictive edge, yielded a p-value of 0.765. This result fails to reach traditional significance levels (p &lt; 0.05), indicating we cannot confidently rule out that our profits occurred by random chance rather than systematic edge.</p>
<p>Power analysis suggests our 342-bet sample achieved approximately 62% statistical power, substantially below standards recommended for reliable conclusions. Based on our observed effect size and variance, we would aim for over 1000 bets to achieve adequate statistical power for definitive validation. These findings highlight a fundamental challenge in sports betting research: the high variance environment demands much larger sample sizes than typical analytical applications to distinguish consistent edges from random variation.</p>
</section>
<section id="market-efficiency-and-sportsbook-performance" class="level3">
<h3 class="anchored" data-anchor-id="market-efficiency-and-sportsbook-performance">Market Efficiency and Sportsbook Performance</h3>
<p>Our analysis revealed significant profit variations across both prop types and individual sportsbooks. Different betting markets showed substantially different results:</p>
<ul>
<li><strong>hits_over_1.5</strong> (at least 2 hits): 18.2% ROI (112 bets)</li>
<li><strong>hits_over_0.5</strong> (at least 1 hit): -0.5% ROI (178 bets)</li>
<li><strong>total_bases_over_1.5</strong> (at least 2 total bases): -6.9% ROI (52 bets)</li>
</ul>
<p>This segmented performance pattern across prop types is noteworthy given that our underlying ML model achieved similar predictive accuracy across all three target markets when validated against actual game outcomes. The dramatic differences in betting profitability—despite comparable model performance—hints at varying levels of pricing efficiency across these markets. This suggests certain prop markets may have more opportunity for profit than others, potentially due to differences in betting volume, public attention, or line pricing errors.</p>
<p>Performance also varied substantially across individual sportsbooks. The most profitable books included Fanatics ($7,252 profit, 72 bets), DraftKings ($2,121 profit, 14 bets), and FanDuel ($1,032 profit, 82 bets).</p>
</section>
<section id="practical-implementation-and-future-directions" class="level3">
<h3 class="anchored" data-anchor-id="practical-implementation-and-future-directions">Practical Implementation and Future Directions</h3>
<p>The machine learning approach offers scalable EV prop identification capabilities that complement situational matchup analysis found in the dashboard. While manual approaches excel at identifying specific advantages through contextual factors, systematic ML evaluation provides consistent statistical criteria across hundreds of daily opportunities, suggesting promising directions for future research integrating algorithmic and human expertise in sports betting applications.</p>
</section>
</section>
</section>
<section id="conclusions" class="level1">
<h1>Conclusions</h1>
<p>The following findings summarize the most important insights from our analyses. They are organized into two categories– Over/Under Runs Bets and Prop Bets to distinguish between team-level and player-level perspectives.</p>
<section id="overunder-runs-bets" class="level2">
<h2 class="anchored" data-anchor-id="overunder-runs-bets">Over/Under Runs Bets</h2>
<p>The first key finding is that bullpen performance is a major driver of scoring, with relief pitcher metrics, particularly ERA and innings pitched, proving to be strong predictors of team run totals, often surpassing the predictive value of starter statistics. This is intuitive: when a starting pitcher struggles, they are removed early, increasing reliance on the bullpen and creating opportunities to exploit fatigue or depth mismatches. In future work, incorporating contextual bullpen data—such as relievers’ recent usage or rest days—could further enhance predictive power.</p>
<p>Next, we found that expected statistics can signal potential shifts in scoring. Differences between a team’s actual batting average and its expected batting average (xBA) often serve as early indicators of offensive changes. Teams outperforming their xBA may be benefiting from favorable luck or other unsustainable factors, suggesting a potential decline in future production. Conversely, teams underperforming their xBA may be making quality contact without seeing results, indicating a likely increase in their amount of hits in the future and thus run production as performance normalizes. However, these signals should always be considered in context, accounting for factors such as ballpark effects, strength of schedule, and injuries. Tracking these gaps offers a valuable tool for anticipating both upward and downward scoring trends.</p>
<p>Lastly, recent team performance emerged as a significant factor when evaluating the over/under metric. In particular, trends in run production and hit totals over the last five games provide valuable context for predicting future scoring outcomes. A team averaging a high number of runs and hits in this short span may be in the midst of an offensive surge, benefiting from hot hitters, favorable matchups, or advantageous ballpark conditions. Conversely, a recent slump in both categories can signal an offense struggling to generate and capitalize on consistent scoring opportunities. Incorporating these short-term trends alongside season-long metrics allows for a more context-driven assessment of a team’s current scoring potential.</p>
</section>
<section id="prop-bets" class="level2">
<h2 class="anchored" data-anchor-id="prop-bets">Prop Bets</h2>
<p>In our prop bet analysis, we examined two key outcomes: whether a player would record at least one hit and whether they would surpass 1.5 total bases. To approach this from multiple angles, we combined domain knowledge with statistical modeling– evaluating matchup history as a potential predictor while also incorporating run value, a more advanced metric of offensive contribution. The findings from these analyses are outlined below.</p>
<ul>
<li><p><strong>Hit Prop Bets</strong>: A $10 wager on every player featured in the dashboard to record at least one hit would have yielded a total profit of $70.</p></li>
<li><p><strong>Total Bases Prop Bets</strong>: A $10 wager on every player featured in the dashboard to exceed 1.5 total bases would have resulted in a total loss of $120.</p></li>
</ul>
<p>The dashboard appeared to predict the hits prop bets reasonably well but was less effective in forecasting the over 1.5 total bases outcome. Thus, incorporating slugging percentage (SLG) into our over 1.5 total bases prop could be highly beneficial. SLG is calculated by dividing a player’s total bases by their at-bats, with singles counting as one base, doubles as two, triples as three, and home runs as four. Unlike batting average, which values all hits equally, SLG places greater weight on extra-base hits, making it a stronger indicator of a player’s potential to exceed 1.5 total bases in a single game.</p>
<p>Incorporating additional context could improve overall accuracy for both props as well. For example, a player’s position in the batting order can be important– batting first versus ninth significantly impacts the number of plate appearances, with higher spots in the lineup typically guaranteeing more opportunities. Home and away status also matters: an away team is assured nine full innings of offense, while a home team leading after the top of the ninth will not bat in the bottom half, losing a potential at-bat. In betting, every opportunity matters, and maximizing them can improve results.</p>
<p>Ballpark-specific performance is another valuable consideration. Some hitters excel in certain parks due to their dimensions; for instance, Fenway Park’s short distance and tall wall in left field can favor hitters who frequently pull the ball to that side. Conversely, some players may struggle in certain stadiums if background elements make it harder to track pitches. Considering these situational factors, along with player statistics at specific venues, the number of variables we could account for is virtually endless. It ranges from the home plate umpire’s strike zone tendencies to weather conditions such as wind speed, temperature, and humidity– all of which can influence offensive performance. Factoring in any combination of these elements could further refine and enhance the dashboard’s predictive power in future versions.</p>
<p>Achieved positive ROI through a systematic approach, generating a 1.95% ROI ($2,579.21 profit on $132,518.08 wagered) across 342 betting opportunities. This demonstrates that data-driven approaches can identify profitable opportunities in MLB player prop markets.</p>
<p>The analysis revealed dramatic profitability differences across prop types, with hits_over_1.5 bets generating an 18.2% ROI, while hits_over_0.5 and total_bases_over_1.5 markets were near breakeven. These results suggest that certain player prop markets are less efficiently priced.</p>
<p>Despite those positive returns, comprehensive statistical testing, including a bootstrap analysis with a p-value of 0.765, could not definitively rule out that the profits occurred by chance. This underscores the substantial sample sizes required for reliable validation in high-variance sports betting environments.</p>
</section>
<section id="implications" class="level2">
<h2 class="anchored" data-anchor-id="implications">Implications</h2>
<p>Our research demonstrates that analytical approaches to MLB betting market analysis can identify potential value opportunities across both team-level and individual player markets. The combination of team scoring models, individual prop prediction, and interactive matchup analysis creates a comprehensive framework for market evaluation that addresses multiple betting contexts within professional baseball.</p>
<p>The hybrid methodology successfully bridges traditional statistical analysis with modern machine learning techniques while maintaining academic rigor through proper validation and data leakage prevention. This approach provides a replicable framework for sports betting research that prioritizes methodological soundness over inflated performance claims, contributing to more reliable research standards in this emerging field.</p>
<p>The solid performance achieved by our models—clustering around established academic baselines—validates market efficiency research suggesting that sustainable edges in professional sports betting are necessarily modest. Rather than claiming exceptional results, our work establishes realistic expectations for legitimate MLB prediction models and provides tools for comprehensive market analysis.</p>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Galekwa2024" class="csl-entry" role="listitem">
Galekwa, René Manassé, and colleagues. 2024. <span>“A Systematic Review of Machine Learning in Sports Betting: Techniques, Challenges, and Future Directions.”</span> <em>arXiv Preprint arXiv:2410.21484</em>. <a href="https://arxiv.org/html/2410.21484v1">https://arxiv.org/html/2410.21484v1</a>.
</div>
<div id="ref-Huang2021" class="csl-entry" role="listitem">
Huang, Mei-Ling, and Yi-Zhen Li. 2021. <span>“Use of Machine Learning and Deep Learning to Predict the Outcomes of Major League Baseball Matches.”</span> <em>Applied Sciences</em> 11 (10): 4499. <a href="https://doi.org/10.3390/app11104499">https://doi.org/10.3390/app11104499</a>.
</div>
<div id="ref-Hubacek2019" class="csl-entry" role="listitem">
Hubáček, Ondřej, Gustav Šourek, and Filip Železný. 2019. <span>“Exploiting Sports-Betting Market Using Machine Learning.”</span> <em>Applied Soft Computing</em> 83: 105654. <a href="https://doi.org/10.1016/j.asoc.2019.105654">https://doi.org/10.1016/j.asoc.2019.105654</a>.
</div>
<div id="ref-Li2022" class="csl-entry" role="listitem">
Li, Shuo-Fang, Mei-Ling Huang, and Yi-Zhen Li. 2022. <span>“Exploring and Selecting Features to Predict the Next Outcomes of MLB Games.”</span> <em>Entropy</em> 24 (2): 264. <a href="https://doi.org/10.3390/e24020264">https://doi.org/10.3390/e24020264</a>.
</div>
<div id="ref-AllThePicksEdge2023" class="csl-entry" role="listitem">
Naomi. 2023. <span>“The Sportsbook Edge: Understanding How the House Always Wins.”</span> <a href="https://allthepicks.com/betting-edge/">https://allthepicks.com/betting-edge/</a>.
</div>
<div id="ref-Vandenbruaene2022" class="csl-entry" role="listitem">
Vandenbruaene, Jonas, Jan Annaert, and Marc De Ceuster. 2022. <span>“Efficient Spread Betting Markets: A Literature Review.”</span> <em>Journal of Sports Economics</em> 23 (4): 442–79. <a href="https://doi.org/10.1177/15270025211071042">https://doi.org/10.1177/15270025211071042</a>.
</div>
<div id="ref-Walsh2024" class="csl-entry" role="listitem">
Walsh, Sean, and Mayukh Joshi. 2024. <span>“Machine Learning for Sports Betting: Should Model Selection Be Based on Accuracy or Calibration?”</span> <em>Finance Research Letters</em> 60: 104814. <a href="https://doi.org/10.1016/j.frl.2024.104814">https://doi.org/10.1016/j.frl.2024.104814</a>.
</div>
</div>
</section>
<section id="appendix" class="level1">
<h1>Appendix</h1>
<p>The following appendix provides supporting materials that complement the main analysis.</p>
<section id="data-dictionary" class="level2">
<h2 class="anchored" data-anchor-id="data-dictionary">Data Dictionaries</h2>
<div class="callout callout-style-default callout-note callout-titled" title="batter_pitches">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
batter_pitches
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table contains underlying aggregated statisical data, which will not show up in the typical box score.(Baseball Savant)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 25%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>batter_id</code></td>
<td>Batter ID</td>
<td>Unique identifier for the batter.</td>
</tr>
<tr class="even">
<td><code>pitch_name</code></td>
<td>Pitch Type</td>
<td>Name of the pitch type (e.g., fastball, slider).</td>
</tr>
<tr class="odd">
<td><code>rv_100</code></td>
<td>Run Value / 100 Pitches</td>
<td>Average run value per 100 pitches seen. Measures how well batters hit each pitch.</td>
</tr>
<tr class="even">
<td><code>rv</code></td>
<td>Run Value</td>
<td>Total run value assigned to differnt pitches the batter has seen.</td>
</tr>
<tr class="odd">
<td><code>pitches</code></td>
<td>Pitches</td>
<td>Total number of pitches thrown or seen.</td>
</tr>
<tr class="even">
<td><code>pitch_usage</code></td>
<td>Pitch Usage</td>
<td>Percentage of time a specific pitch type is used.</td>
</tr>
<tr class="odd">
<td><code>pa</code></td>
<td>Plate Appearances</td>
<td>Number of completed batting appearances, including walks and hit-by-pitches.</td>
</tr>
<tr class="even">
<td><code>ba</code></td>
<td>Batting Average</td>
<td>Hits divided by at-bats.</td>
</tr>
<tr class="odd">
<td><code>x_ba</code></td>
<td>Expected Batting Average</td>
<td>Likelihood a batted ball becomes a hit, based on exit velocity and launch angle.</td>
</tr>
<tr class="even">
<td><code>slg</code></td>
<td>Slugging Percentage</td>
<td>Total bases divided by at-bats; measures power.</td>
</tr>
<tr class="odd">
<td><code>x_slg</code></td>
<td>Expected Slugging</td>
<td>Predicted slugging based on batted ball quality.</td>
</tr>
<tr class="even">
<td><code>woba</code></td>
<td>Weighted On-Base Average</td>
<td>Gives more weight to extra-base hits than OBP (On Base Percentage).</td>
</tr>
<tr class="odd">
<td><code>x_woba</code></td>
<td>Expected wOBA</td>
<td>Predicted wOBA using quality-of-contact data.</td>
</tr>
<tr class="even">
<td><code>whiff_percent</code></td>
<td>Whiff Percentage</td>
<td>Percentage of swings that result in misses.</td>
</tr>
<tr class="odd">
<td><code>k_percent</code></td>
<td>Strikeout Percentage</td>
<td>Strikeouts divided by plate appearances.</td>
</tr>
<tr class="even">
<td><code>put_away</code></td>
<td>Put Away Percentage</td>
<td>2-strike pitches resulting in strikeouts divided by total 2-strike pitches.</td>
</tr>
<tr class="odd">
<td><code>hard_hit</code></td>
<td>Hard Hit Percentage</td>
<td>Percentage of batted balls hit at 95+ mph.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="batter_statcast">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
batter_statcast
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table contains aggregated Statcast metrics for batters across different pitch types, including expected and actual performance differentials across batting average, slugging, and wOBA. (Baseball Savant)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 25%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>batter_id</code></td>
<td>Batter ID</td>
<td>Unique identifier for the batter.</td>
</tr>
<tr class="even">
<td><code>season</code></td>
<td>Season</td>
<td>Year in which the statistics are from.</td>
</tr>
<tr class="odd">
<td><code>pa</code></td>
<td>Plate Appearances</td>
<td>Number of completed batting appearances, including walks and hit-by-pitches.</td>
</tr>
<tr class="even">
<td><code>bip</code></td>
<td>Balls In Play</td>
<td>Number of batted balls put into play (excluding strikeouts, walks, etc.).</td>
</tr>
<tr class="odd">
<td><code>ba</code></td>
<td>Batting Average</td>
<td>Hits divided by at-bats.</td>
</tr>
<tr class="even">
<td><code>x_ba</code></td>
<td>Expected Batting Average</td>
<td>Likelihood a batted ball becomes a hit, based on exit velocity and launch angle.</td>
</tr>
<tr class="odd">
<td><code>diff_ba</code></td>
<td>BA - xBA</td>
<td>Difference between actual and expected batting average.</td>
</tr>
<tr class="even">
<td><code>slg</code></td>
<td>Slugging Percentage</td>
<td>Total bases divided by at-bats; measures power.</td>
</tr>
<tr class="odd">
<td><code>x_slg</code></td>
<td>Expected Slugging</td>
<td>Predicted slugging based on batted ball quality.</td>
</tr>
<tr class="even">
<td><code>diff_slg</code></td>
<td>SLG - xSLG</td>
<td>Difference between actual and expected slugging percentage.</td>
</tr>
<tr class="odd">
<td><code>woba</code></td>
<td>Weighted On-Base Average</td>
<td>Gives more weight to extra-base hits than OBP.</td>
</tr>
<tr class="even">
<td><code>x_woba</code></td>
<td>Expected wOBA</td>
<td>Predicted wOBA using quality-of-contact data.</td>
</tr>
<tr class="odd">
<td><code>diff_woba</code></td>
<td>wOBA - xwOBA</td>
<td>Difference between actual and expected wOBA.</td>
</tr>
<tr class="even">
<td><code>batter_id</code></td>
<td>Batter ID</td>
<td>Unique identifier for the batter.</td>
</tr>
<tr class="odd">
<td><code>ops</code></td>
<td>OPS</td>
<td>On-base Plus Slugging — combines on-base % and slugging % to summarize hitter performance.</td>
</tr>
<tr class="even">
<td><code>wrc_plus</code></td>
<td>wRC+</td>
<td>Weighted Runs Created Plus — measures a player’s total offensive value, adjusted for park and league. 100 is league average.</td>
</tr>
<tr class="odd">
<td><code>home_runs</code></td>
<td>Home Runs</td>
<td>Number of home runs hit by the player.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="batter_stats">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
batter_stats
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table captures traditional game-level statistics for each batter, derived from box score data. (statsapi)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 18%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>game_id</code></td>
<td>Game ID</td>
<td>Unique identifier for the game.</td>
</tr>
<tr class="even">
<td><code>batter_id</code></td>
<td>Batter ID</td>
<td>Unique identifier for the batter.</td>
</tr>
<tr class="odd">
<td><code>team_id</code></td>
<td>Team ID</td>
<td>Identifier for the team the batter played for in the game.</td>
</tr>
<tr class="even">
<td><code>position</code></td>
<td>Position</td>
<td>Fielding position the batter played during the game.</td>
</tr>
<tr class="odd">
<td><code>ab</code></td>
<td>At-Bats</td>
<td>Number of official at-bats (excludes walks, HBP, sacrifices).</td>
</tr>
<tr class="even">
<td><code>h</code></td>
<td>Hits</td>
<td>Number of hits.</td>
</tr>
<tr class="odd">
<td><code>bb</code></td>
<td>Walks (BB)</td>
<td>Number of base on balls (walks).</td>
</tr>
<tr class="even">
<td><code>r</code></td>
<td>Runs</td>
<td>Number of runs scored.</td>
</tr>
<tr class="odd">
<td><code>rbi</code></td>
<td>Runs Batted In</td>
<td>Number of runs batted in.</td>
</tr>
<tr class="even">
<td><code>so</code></td>
<td>Strikeouts</td>
<td>Number of times the batter struck out.</td>
</tr>
<tr class="odd">
<td><code>double</code></td>
<td>Doubles</td>
<td>Number of doubles hit.</td>
</tr>
<tr class="even">
<td><code>triple</code></td>
<td>Triples</td>
<td>Number of triples hit.</td>
</tr>
<tr class="odd">
<td><code>hr</code></td>
<td>Home Runs</td>
<td>Number of home runs hit.</td>
</tr>
<tr class="even">
<td><code>sb</code></td>
<td>Stolen Bases</td>
<td>Number of bases stolen during the game.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="previews">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
previews
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table stores pre-game matchup context, such as historical batter-vs-pitcher performance, scraped from MLB.com preview pages. (Selenium)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 17%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>game_date</code></td>
<td>Game Date</td>
<td>Date of the game.</td>
</tr>
<tr class="even">
<td><code>batter_name</code></td>
<td>Batter Name</td>
<td>Name of the batter (no ID available in this table).</td>
</tr>
<tr class="odd">
<td><code>pitcher_name</code></td>
<td>Pitcher Name</td>
<td>Name of the opposing pitcher.</td>
</tr>
<tr class="even">
<td><code>hr</code></td>
<td>Home Runs</td>
<td>Total number of home runs prior to the game against the projected pitcher.</td>
</tr>
<tr class="odd">
<td><code>rbi</code></td>
<td>Runs Batted In</td>
<td>Total number of RBIs prior to the game against the projected pitcher.</td>
</tr>
<tr class="even">
<td><code>ab</code></td>
<td>At-Bats</td>
<td>Number of official at-bats prior to the game against the projected pitcher.</td>
</tr>
<tr class="odd">
<td><code>avg</code></td>
<td>Batting Average</td>
<td>Batting average prior to the game against the projected pitcher.</td>
</tr>
<tr class="even">
<td><code>ops</code></td>
<td>On-Base Plus Slugging</td>
<td>OPS (OBP + SLG) prior to the game against the projected pitcher.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="players">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
players
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table contains player metadata, including full names and unique identifiers used to join across tables. (statsapi)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 20%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>player_id</code></td>
<td>Player ID</td>
<td>Unique identifier for the player.</td>
</tr>
<tr class="even">
<td><code>player_name</code></td>
<td>Player Name</td>
<td>Full name of the player.</td>
</tr>
<tr class="odd">
<td><code>bats</code></td>
<td>Bats</td>
<td>Which side they hit from (Left or Right).</td>
</tr>
<tr class="even">
<td><code>throws</code></td>
<td>Throws</td>
<td>Which side they pitch from (Left or Right).</td>
</tr>
<tr class="odd">
<td><code>birth_date</code></td>
<td>Birth Date</td>
<td>Day player was born.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="sides">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
sides
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table maps each team to its role in a given game (home or away), used to differentiate sides during analysis. (statsapi)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>game_id</code></td>
<td>Game ID</td>
<td>Identifier for the game.</td>
</tr>
<tr class="even">
<td><code>team_id</code></td>
<td>Team ID</td>
<td>Identifier for the team.</td>
</tr>
<tr class="odd">
<td><code>side</code></td>
<td>Side</td>
<td>Side of the team in the game (<code>home</code> or <code>away</code>).</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="teams">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
teams
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table contains metadata about each team, including their unique identifier and full name. (statsapi)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 20%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>team_id</code></td>
<td>Team ID</td>
<td>Unique identifier for the team.</td>
</tr>
<tr class="even">
<td><code>team_name</code></td>
<td>Team Name</td>
<td>Full name of the team.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="games">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
games
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table holds game-level information such as date and final scores for both home and away teams. (statsapi)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 19%">
<col style="width: 62%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>game_id</code></td>
<td>Game ID</td>
<td>Unique identifier for the game.</td>
</tr>
<tr class="even">
<td><code>date</code></td>
<td>Date</td>
<td>Date the game was played.</td>
</tr>
<tr class="odd">
<td><code>home_team_id</code></td>
<td>Home Team ID</td>
<td>Identifier for the home team.</td>
</tr>
<tr class="even">
<td><code>home_score</code></td>
<td>Home Team Score</td>
<td>Final score of the home team.</td>
</tr>
<tr class="odd">
<td><code>away_team_id</code></td>
<td>Away Team ID</td>
<td>Identifier for the away team.</td>
</tr>
<tr class="even">
<td><code>away_score</code></td>
<td>Away Team Score</td>
<td>Final score of the away team.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="pitches">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
pitches
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table contains pitch-level Statcast data used for machine learning feature engineering, derived from individual pitch outcomes. (pybaseball)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>game_id</code></td>
<td>Game ID</td>
<td>Unique identifier for games table.</td>
</tr>
<tr class="even">
<td><code>batter_id</code></td>
<td>Batter ID</td>
<td>Unique identifier for batters.</td>
</tr>
<tr class="odd">
<td><code>pitcher_id</code></td>
<td>Pitcher ID</td>
<td>Unique identifier for pitchers.</td>
</tr>
<tr class="even">
<td><code>events</code></td>
<td>Pitch Outcome</td>
<td>Result of the plate appearance (single, home_run, strikeout, etc.).</td>
</tr>
<tr class="odd">
<td><code>launch_speed</code></td>
<td>Exit Velocity</td>
<td>Speed of batted ball off the bat in mph.</td>
</tr>
<tr class="even">
<td><code>launch_angle</code></td>
<td>Launch Angle</td>
<td>Vertical angle of batted ball trajectory in degrees.</td>
</tr>
<tr class="odd">
<td><code>release_speed</code></td>
<td>Pitch Velocity</td>
<td>Speed of pitch when released in mph.</td>
</tr>
<tr class="even">
<td><code>pitch_type</code></td>
<td>Pitch Type Code</td>
<td>Abbreviated pitch type (FF=four-seam fastball, SL=slider, etc.).</td>
</tr>
<tr class="odd">
<td><code>woba_value</code></td>
<td>Weighted On-Base Value</td>
<td>Run value assigned to the specific pitch outcome.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="pitcher_stats">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
pitcher_stats
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table contains game-level performance stats for each pitcher, including innings pitched, runs allowed, and ERA. (statsapi)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 19%">
<col style="width: 62%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>game_id</code></td>
<td>Game ID</td>
<td>Unique identifier for the game.</td>
</tr>
<tr class="even">
<td><code>pitcher_id</code></td>
<td>Pitcher ID</td>
<td>Unique identifier for the pitcher.</td>
</tr>
<tr class="odd">
<td><code>team_id</code></td>
<td>Team ID</td>
<td>Identifier for the team the pitcher played for.</td>
</tr>
<tr class="even">
<td><code>type</code></td>
<td>Pitcher Type</td>
<td>Type of pitcher (e.g., starter, reliever).</td>
</tr>
<tr class="odd">
<td><code>ip</code></td>
<td>Innings Pitched</td>
<td>Total number of innings pitched in the game.</td>
</tr>
<tr class="even">
<td><code>h</code></td>
<td>Hits Allowed</td>
<td>Total hits allowed.</td>
</tr>
<tr class="odd">
<td><code>r</code></td>
<td>Runs Allowed</td>
<td>Total runs allowed.</td>
</tr>
<tr class="even">
<td><code>er</code></td>
<td>Earned Runs</td>
<td>Number of earned runs allowed.</td>
</tr>
<tr class="odd">
<td><code>bb</code></td>
<td>Walks</td>
<td>Number of walks issued.</td>
</tr>
<tr class="even">
<td><code>so</code></td>
<td>Strikeouts</td>
<td>Number of batters struck out.</td>
</tr>
<tr class="odd">
<td><code>hr</code></td>
<td>Home Runs Allowed</td>
<td>Number of home runs allowed.</td>
</tr>
<tr class="even">
<td><code>pitches</code></td>
<td>Pitches Thrown</td>
<td>Total number of pitches thrown.</td>
</tr>
<tr class="odd">
<td><code>strikes</code></td>
<td>Strikes Thrown</td>
<td>Number of strikes thrown.</td>
</tr>
<tr class="even">
<td><code>era</code></td>
<td>Earned Run Average</td>
<td>ERA for the game.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="pitcher_statcast">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
pitcher_statcast
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table includes Statcast-derived advanced metrics for pitchers, highlighting differences between actual and expected outcomes like ERA, BA, SLG, and wOBA. (Baseball Savant)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 18%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>pitcher_id</code></td>
<td>Pitcher ID</td>
<td>Unique identifier for the pitcher.</td>
</tr>
<tr class="even">
<td><code>pa</code></td>
<td>Plate Appearances</td>
<td>Number of completed batting appearances against the pitcher.</td>
</tr>
<tr class="odd">
<td><code>bip</code></td>
<td>Balls In Play</td>
<td>Number of batted balls put into play against pitcher.</td>
</tr>
<tr class="even">
<td><code>ba</code></td>
<td>Batting Average</td>
<td>Batting average against the pitcher.</td>
</tr>
<tr class="odd">
<td><code>x_ba</code></td>
<td>Expected BA</td>
<td>Expected batting average based on batted ball data.</td>
</tr>
<tr class="even">
<td><code>diff_ba</code></td>
<td>BA - xBA</td>
<td>Difference between actual and expected batting average.</td>
</tr>
<tr class="odd">
<td><code>slg</code></td>
<td>Slugging Percentage</td>
<td>Slugging percentage against the pitcher.</td>
</tr>
<tr class="even">
<td><code>x_slg</code></td>
<td>Expected SLG</td>
<td>Expected slugging based on contact quality.</td>
</tr>
<tr class="odd">
<td><code>diff_slg</code></td>
<td>SLG - xSLG</td>
<td>Difference between actual and expected slugging.</td>
</tr>
<tr class="even">
<td><code>woba</code></td>
<td>Weighted On-Base Avg</td>
<td>Weighted on-base average against the pitcher.</td>
</tr>
<tr class="odd">
<td><code>x_woba</code></td>
<td>Expected wOBA</td>
<td>Predicted wOBA using Statcast data.</td>
</tr>
<tr class="even">
<td><code>diff_woba</code></td>
<td>wOBA - xwOBA</td>
<td>Difference between actual and expected wOBA.</td>
</tr>
<tr class="odd">
<td><code>era</code></td>
<td>ERA</td>
<td>Earned run average.</td>
</tr>
<tr class="even">
<td><code>x_era</code></td>
<td>Expected ERA</td>
<td>Expected ERA based on contact and strikeout/walk profile.</td>
</tr>
<tr class="odd">
<td><code>diff_era</code></td>
<td>ERA - xERA</td>
<td>Difference between actual and expected ERA.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="pitcher_pitches">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
pitcher_pitches
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table contains pitch-type-level metrics for pitchers, including run value, whiff rate, usage rate, and contact quality outcomes. (Baseball Savant)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 62%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>pitcher_id</code></td>
<td>Pitcher ID</td>
<td>Unique identifier for the pitcher.</td>
</tr>
<tr class="even">
<td><code>pitch_name</code></td>
<td>Pitch Type</td>
<td>Name of the pitch (e.g., fastball, slider).</td>
</tr>
<tr class="odd">
<td><code>rv_100</code></td>
<td>Run Value / 100 Pitches</td>
<td>Average run value per 100 pitches thrown.</td>
</tr>
<tr class="even">
<td><code>rv</code></td>
<td>Run Value</td>
<td>Total run value assigned to the pitch.</td>
</tr>
<tr class="odd">
<td><code>pitches</code></td>
<td>Pitches Thrown</td>
<td>Number of times this pitch type was thrown.</td>
</tr>
<tr class="even">
<td><code>pitch_usage</code></td>
<td>Pitch Usage</td>
<td>Percentage of time this pitch type is used.</td>
</tr>
<tr class="odd">
<td><code>pa</code></td>
<td>Plate Appearances</td>
<td>Total plate appearances ending with this pitch type.</td>
</tr>
<tr class="even">
<td><code>ba</code></td>
<td>Batting Average</td>
<td>Batting average against this pitch.</td>
</tr>
<tr class="odd">
<td><code>x_ba</code></td>
<td>Expected BA</td>
<td>Expected batting average against this pitch.</td>
</tr>
<tr class="even">
<td><code>slg</code></td>
<td>Slugging Percentage</td>
<td>Slugging percentage against this pitch.</td>
</tr>
<tr class="odd">
<td><code>x_slg</code></td>
<td>Expected SLG</td>
<td>Expected slugging against this pitch.</td>
</tr>
<tr class="even">
<td><code>woba</code></td>
<td>Weighted On-Base Average</td>
<td>wOBA against this pitch.</td>
</tr>
<tr class="odd">
<td><code>x_woba</code></td>
<td>Expected wOBA</td>
<td>Expected wOBA against this pitch.</td>
</tr>
<tr class="even">
<td><code>whiff_percent</code></td>
<td>Whiff Percentage</td>
<td>Percent of swings against this pitch that missed.</td>
</tr>
<tr class="odd">
<td><code>k_percent</code></td>
<td>Strikeout Percentage</td>
<td>Percent of plate appearances ending in strikeouts on this pitch.</td>
</tr>
<tr class="even">
<td><code>put_away</code></td>
<td>Put Away Percentage</td>
<td>Percent of 2-strike counts resulting in strikeouts with this pitch.</td>
</tr>
<tr class="odd">
<td><code>hard_hit</code></td>
<td>Hard Hit Percentage</td>
<td>Percent of batted balls hit 95+ mph off this pitch.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="betting_events">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
betting_events
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table links betting markets to scheduled or completed games. (oddsapi)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 18%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>event_id</code></td>
<td>Event ID</td>
<td>Unique identifier for each betting event.</td>
</tr>
<tr class="even">
<td><code>commence_date</code></td>
<td>Start Time</td>
<td>Scheduled start date of the game.</td>
</tr>
<tr class="odd">
<td><code>home_team</code></td>
<td>Home Team</td>
<td>Name of the home team.</td>
</tr>
<tr class="even">
<td><code>away_team</code></td>
<td>Away Team</td>
<td>Name of the away team.</td>
</tr>
<tr class="odd">
<td><code>completed</code></td>
<td>Completed Flag</td>
<td>Boolean indicating whether the event has finished.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="player_props">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
player_props
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This table represents the planned betting market integration, designed to support model validation and value identification once populated with historical odds data. (oddsapi)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>prop_id</code></td>
<td>Prop ID</td>
<td>Primary key for individual prop bet offerings.</td>
</tr>
<tr class="even">
<td><code>event_id</code></td>
<td>Event ID</td>
<td>Links to specific games through events table.</td>
</tr>
<tr class="odd">
<td><code>bookmaker_key</code></td>
<td>Sportsbook</td>
<td>Identifier for which bookmaker offered the odds.</td>
</tr>
<tr class="even">
<td><code>market_type</code></td>
<td>Bet Type</td>
<td>Type of prop bet (hits, total_bases, home_runs, etc.).</td>
</tr>
<tr class="odd">
<td><code>player_name</code></td>
<td>Player Name</td>
<td>Name of player for the prop bet.</td>
</tr>
<tr class="even">
<td><code>price</code></td>
<td>Betting Odds</td>
<td>Decimal odds offered by bookmaker.</td>
</tr>
<tr class="odd">
<td><code>point</code></td>
<td>Over/Under Line</td>
<td>Threshold value for over/under bets (0.5, 1.5, etc.).</td>
</tr>
<tr class="even">
<td><code>last_update</code></td>
<td>Last Update</td>
<td>Time at which the prop was last updated.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="bookmakers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
bookmakers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This lookup table provides sportsbook identifiers used in the player_props table.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 19%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Name</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>bookmaker_key</code></td>
<td>Sportsbook Key</td>
<td>Unique identifier for the bookmaker</td>
</tr>
<tr class="even">
<td><code>title</code></td>
<td>Sportsbook Name</td>
<td>Display name of the sportsbook (e.g., “DraftKings”, “FanDuel”, etc.).</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>